# Generated by Django 5.2.7 on 2025-10-17 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('SCI_FI', 'Science Fiction'), ('MYSTERY', 'Mystery'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('HISTORICAL', 'Historical Fiction'), ('BIOGRAPHY', 'Biography'), ('SELF_HELP', 'Self Help'), ('BUSINESS', 'Business'), ('SCIENCE', 'Science'), ('TECHNOLOGY', 'Technology'), ('ART', 'Art'), ('COOKING', 'Cooking'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='FICTION', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('daily_rental_price', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('cover_image', models.ImageField(blank=True, default='book_covers/default_cover.jpg', null=True, upload_to='book_covers/')),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
